server:
  port: 8080
  main:
    allow-circular-references: true
spring:
  shardingsphere:
    datasource:
      names: db1,db2
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.109:3306/bitchpeng?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Pj0556-7512525
      db2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.115:3306/bitchpeng?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Pj0556-7512525
    rules:
      sharding:
        key-generators: # 分布式主键
          alg-snowflake:  # 222 自定义主键名称
            type: SNOWFLAKE  # 分布式序列-算法类型
        sharding-algorithms:  # 定义分片算法
          table-inline: # 1111 自定义分片算法名称
            type: INLINE # 分片算法类型: 行表达式分片算法(标准分片算法下包含->行表达式分片算法)
            props:
              algorithm-expression: t_course_$->{cid % 2 + 1} # 分片算法属性配置
        tables:
          # 垂直分库
          pay_order:
            actual-data-nodes: db1.pay_order
          users:
            actual-data-nodes: db2.users



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
