server:
  port: 8080
  main:
    allow-circular-references: true
spring:
  shardingsphere:
    datasource:
      names: db1
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.109:3306/bitchpeng?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Pj0556-7512525
    rules:
      sharding:
        key-generators: # 分布式主键
          alg-snowflake:  # 222 自定义主键名称
            type: SNOWFLAKE  # 分布式序列-算法类型
        sharding-algorithms:  # 定义分片算法
          table-inline: # 1111 自定义分片算法名称
            type: INLINE # 分片算法类型: 行表达式分片算法(标准分片算法下包含->行表达式分片算法)
            props:
              algorithm-expression: t_course_$->{cid % 2 + 1} # 分片算法属性配置
        tables:
          # 水平分表 将单个数据库内的表分开
          t_course: # 逻辑表名称
            actual-data-nodes: db1.t_course_$->{0..1} # 数据节点
            key-generate-strategy:
              column: cid  # 分布式序列-列名称
              key-generator-name: alg-snowflake  # 222分布式序列-算法名称
            table-strategy:
              standard:
                sharding-column: cid # 分片键名称
                sharding-algorithm-name: table-inline # 1111 自定义分片算法名称



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
